import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigationbar } from "@/components/Navigationbar/Navigationbar";
import { Providers } from "@/components/Providers";
import { cookies } from "next/headers";
import { UserResponse } from "@/dto/userResponse";
import { fetchUserData } from "./lib/actions";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedIn = cookies().has("accessToken");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navigationbar isAuthorized={loggedIn}></Navigationbar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
